---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - {title: "Home", href: https://jrcheng10.github.io/, align: left}
      - {title: "About", href: about.html, align: right }
      - {icon: fa-envelope, href: mailto:<cheng.john.r@gmail.com>, align: right }
      - {icon: fa-github, href: https://github.com/jrcheng10/, align: right }
      - {icon: fa-linkedin, href: https://www.linkedin.com/in/john-c-843a2a37/, align: right }

---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
library(ggplot2)
```

```{r import}
data("instacart")
```

Column {data-width=600}
-----------------------------------------------------------------------

### Most Popular Tea Brands on Instacart

```{r bar_plot}
instacart %>%
  filter(aisle == "tea") %>%
  group_by(product_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(15) %>%
  mutate(product_name = fct_reorder(product_name, count, .desc = TRUE)) %>% 
  plot_ly(x = ~product_name, y = ~count, color = ~product_name, type = "bar", colors = "viridis") %>% 
  layout(xaxis = list(tickangle = 315, title = "Tea Brand"),
         yaxis = list(title = "Order Count"),
         legend = list(font = list(size = 10)))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Distribution of Purchase Times for Top Alcoholic Drinks on Instacart

```{r density_plot, fig.width = 8}
alcohol = instacart %>%
  filter(department == "alcohol") %>%
  group_by(product_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(5)

alcohol_times = instacart %>%
  filter(product_name %in% alcohol$product_name) %>%
  group_by(product_name, order_hour_of_day) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = order_hour_of_day, fill = product_name)) +
  geom_density(alpha = .5) +
  scale_x_continuous(
    breaks = c(3, 6, 9, 12, 15, 18, 21),
    labels = c("3am", "6am", "9am", "12pm", "3pm", "6pm", "9pm"),
    limits = c(0, 23)
) +
  viridis::scale_fill_viridis(discrete = TRUE)

ggplotly(alcohol_times) %>% 
  layout(legend = list(title = list(text = "")),
         xaxis = list(title = list(text = "Time of Day", font = list(size = 13))),
         yaxis = list(title = list(text = "Density", font = list(size = 13))))
```

### Average Repeat Order Count for Top Ice Cream Brands on Instacart

```{r box_plot}

```